import { ReactNode } from 'react';

import Footer from '@/component/Footer/Footer';
import { HeaderInfo } from '@/component/HeaderInfo/HeaderInfo';
import Navbar from '@/component/Navbar/Navbar';
import { TopBar } from '@/component/TopBar/TopBar';

export const metadata = {
  title: 'SYNERGY MSP',
  description: 'Generated by create next app',
};

interface MainLayoutProps {
  children: ReactNode;
}

const MainLayout: React.FC<MainLayoutProps> = ({ children }) => {
  return (
    <div className='flex min-h-screen flex-col'>
      <TopBar />
      <HeaderInfo />
      <Navbar />
      <main className='flex-1'>{children}</main>
      <Footer />
    </div>
  );
};

export default MainLayout;
